In [2]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC

# Q5. Part1

In [2]:
columns = np.arange(5000)

In [3]:
df_train = pd.read_csv('gisette_train.data', sep = " ", names= columns, index_col=False)

In [4]:
df_train.head()

0     1     2     3     4     5     6     7     8     9     ...  4990  \
0   550     0   495     0     0     0     0   976     0     0  ...     0   
1     0     0     0     0     0     0     0   976     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0   742     0     0     0     0   684     0   956  ...     0   
4     0     0     0     0     0     0     0   608     0   979  ...   991   

   4991  4992  4993  4994  4995  4996  4997  4998  4999  
0     0     0   991   991     0     0     0     0   983  
1   475     0   991     0     0   991     0     0     0  
2     0     0     0     0     0     0     0     0     0  
3     0     0     0     0     0   674     0     0   838  
4     0     0   828     0     0     0     0     0     0  

[5 rows x 5000 columns]

In [5]:
df_train.shape

(6000, 5000)

In [6]:
train_label = pd.read_csv('gisette_train.labels', names = ['label'])
train_label.head()

label
0      1
1     -1
2      1
3      1
4      1

In [7]:
train_label.shape

(6000, 1)

In [8]:
test_label = pd.read_csv('gisette_valid.labels', names = ['label'])

In [9]:
test_label.shape

(1000, 1)

In [10]:
df_test = pd.read_csv('gisette_valid.data', sep = " ", names= columns, index_col=False)

In [11]:
df_test.head()

0     1     2     3     4     5     6     7     8     9     ...  4990  \
0   688     0     0     0     0     0     0   952     0   870  ...     0   
1   778   758     0     0     0     0     0   708     0   991  ...     0   
2   469     0   816     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0   571   991   983     0   983  ...     0   
4     0     0     0     0     0     0     0   949     0   991  ...     0   

   4991  4992  4993  4994  4995  4996  4997  4998  4999  
0     0     0     0     0     0   494     0   769     0  
1     0     0   770     0     0     0     0     0     0  
2     0     0   467     0     0     0   417     0     0  
3     0     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0   976     0  

[5 rows x 5000 columns]

In [12]:
df_test.shape

(1000, 5000)

In [6]:
from sklearn.svm import SVC
model = SVC(kernel="linear")

In [14]:
model.fit(df_train, train_label)

C:\Python\Python39\lib\site-packages\sklearn\utils\validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [15]:
n = model.support_vectors_ 
print(len(n))
print(n)

1084
[[  0.   0. 983. ...   0.   0.   0.]
 [  0.   0. 742. ...   0.   0. 709.]
 [554.   0. 980. ...   0.   0. 654.]
 ...
 [  0.   0.   0. ...   0. 894.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0. 983. ...   0.   0.   0.]]


In [16]:
# for testing error
model.score(df_test, test_label)

0.976

In [17]:
#for training error
model.score(df_train, train_label)

1.0

# Q5 Part 2

# RBF (a.k.a. Gaussian kernel; set γ = 0.001)

In [19]:
model_gauss = SVC(kernel="rbf",gamma= 0.001)

In [20]:
model_gauss.fit(df_train, train_label)

C:\Python\Python39\lib\site-packages\sklearn\utils\validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(gamma=0.001)

In [21]:
m = model_gauss.support_vectors_ 
print(len(m))
print(m)

6000
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0. 983. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0. 486.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0. 886.   0.]]


In [22]:
#for training error
model_gauss.score(df_train, train_label)

1.0

In [23]:
#for testing error
model_gauss.score(df_test, test_label)

0.5

# Polynomial kernel (set degree =2, coef0 = 1)

In [24]:
model_poly = SVC(kernel="poly", degree=2, coef0 =1)

In [25]:
model_poly.fit(df_train, train_label)

C:\Python\Python39\lib\site-packages\sklearn\utils\validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(coef0=1, degree=2, kernel='poly')

In [26]:
o = model_poly.support_vectors_ 
print(len(o))
print(o)

1332
[[  0.   0. 983. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0. 968.   0.]
 ...
 [  0.   0.   0. ...   0. 894.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0. 983. ...   0.   0.   0.]]


In [27]:
#for training error
model_poly.score(df_train, train_label)

0.9995

In [28]:
#for testing error
model_poly.score(df_test, test_label)

0.98